# docker-compose --env-file .env up -d
#or
# set CLOUDFLARE_TUNNEL_TOKEN=your_token
# docker-compose up -d

services:
  frontend:
    # image: woutjuuh02/deelfabriek-kortrijk-2025-frontend:latest
    build:
      context: ./frontend
      # platforms:
      #   - linux/arm64    
    environment:
      - PAYCONIQ_API_KEY=${PAYCONIQ_API_KEY}
      - NEXT_PUBLIC_API_URL=/api
      - BACKEND_URL=http://backend:3001
    ports:
      - "3000:3000"
    restart: unless-stopped

  backend:
    # image: woutjuuh02/deelfabriek-kortrijk-2025-backend:latest
    build:
      context: ./backend
      # platforms:
      #   - linux/arm64
    ports:
      - 3001:3001
    volumes:
      - uploads_data:/app/Uploads
    restart: unless-stopped

  database:
    image: mysql:8.0
    environment:
      - TZ=Europe/Brussels
      - MYSQL_USER=${MYSQL_USER}
      - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}
      - MYSQL_DATABASE=${MYSQL_DATABASE}
    ports:
      - "3306:3306"
    volumes:
      - db_data:/var/lib/mysql
    restart: unless-stopped

  cloudflared:
    image: cloudflare/cloudflared
    container_name: cloudflare-tunnel
    restart: unless-stopped
    command: tunnel --no-autoupdate run
    environment:
      - TUNNEL_TOKEN=${CLOUDFLARE_TUNNEL_TOKEN}
    # in cloudflare panel --> link tunnel naar "http://backend:3001" ipv "http://localhost:3001"
    networks:
      - default

volumes:
  db_data:
  uploads_data:
