# docker-compose --env-file .env up -d
#or
# set CLOUDFLARE_TUNNEL_TOKEN=your_token
# docker-compose up -d

version: "3.8"
services:
  frontend:
    build: ./frontend
    ports:
      - "3000:3000"
    restart: unless-stopped

  backend:
    build:
      context: ./backend
    ports:
      - 3001:3001
    restart: unless-stopped

  database:
    image: mysql:8.0
    environment:
      MYSQL_USER: deelfabriek
      MYSQL_ROOT_PASSWORD: deelfabriek2025
      MYSQL_DATABASE: deelfabriek
    ports:
      - "3306:3306"
    volumes:
      - db_data:/var/lib/mysql
    restart: unless-stopped

  cloudflared:
    image: cloudflare/cloudflared
    container_name: cloudflare-tunnel
    restart: unless-stopped
    command: tunnel --no-autoupdate run
    environment:
      - TUNNEL_TOKEN=${CLOUDFLARE_TUNNEL_TOKEN}
    # in cloudflare panel --> link tunnel naar "http://backend:3001" ipv "http://localhost:3001"
    networks:
      - default

volumes:
  db_data:
