@url = http://0.0.0.0:3001


//USERS 

//werkt
GET {{url}}/users

### 
//werkt
GET {{url}}/users/1

###
// werkt
POST {{url}}/users
Content-Type: application/json

{
  "firstname": "Lisa",
  "lastname": "example",
  "phoneNumber": "32470123456",
  "email": "efhlzeuhfrrrezr@zeuifglz",
  "street": "Main Street 123",
  "city": "Kortrijk",
  "bus": null,
  "postalCode": "2000"
}

###
// werkt
PUT {{url}}/users/1
Content-Type: application/json

{
  "firstname": "Philipp",
  "lastname": "example",
  "phoneNumber": "32470123456",
  "email": "jfeiojfofj.example.com",
  "street": "Main Street 123",
  "city": "Brussels",
  "bus": "02",
  "postalCode": "2000"
  
}
###

//ITEMS
// -------------------------------
###
// all products page  -werkt // only with lockerid
GET {{url}}/items
###
// detail product page  -werkt
GET {{url}}/items/2
###
// get item with status available 
// Werkt
GET {{url}}/items/available
###
//Werkt
GET {{url}}/items?categoryId=3
Accept: application/json
###

//CATEGORIES
// -------------------------------
// werkt
GET {{url}}/categories
###

// reservations
// -------------------------------
// werkt
POST {{url}}/reservations
Content-Type: application/json

{
  "itemId": 4,
  "userId": 1,
  "weeks": 2
}

// get reservations for user
###
// nog output maken 
GET {{url}}/reservations/3

###
// get opening hours
GET {{url}}/openingshours




GET {{url}}/reservations/9
###
GET {{url}}/reservations/code/611838
###
PUT {{url}}/reservations/code/611838/ispayed


