@url = http://localhost:5159

//USERS 


GET {{url}}/admin/users

### 
GET {{url}}/admin/users/1

###
PUT {{url}}/admin/users/1
Content-Type: application/json

{
  "firstname": "Philipp",
  "lastname": "example",
  "phoneNumber": "32470123456",
  "email": "Philipp.example.com",
  "street": "Main Street 123",
  "city": "Brussels",
  "bus": "02",
  "postalCode": "2000"
  
}
###(
DELETE {{url}}/admin/users/3
###
//ITEMS
// -------------------------------

GET {{url}}/admin/items
###
// there is an api that also sends the image to upload and stores the png in database http://localhost:5159/admin/items/with-image (api name still needs to change)  
POST {{url}}/admin/items
Content-Type: application/json

{
  "Title": "machine",
  "description": "Sterke elektrische boormachine voor thuisgebruik",
  "pricePerWeek": 11.50,
  "status": 3,
  "ImageSrc": "https://example.com/images/boormachine.jpg",
  "howToUse": "Gebruik met beschermbril.",
  "Accesories": "Boormachine, oplader, handleiding",
  "weight": 2.5,
  "dimensions": "30x20 cm",
  "tip": "Gebruik lage snelheid voor hout.",
  "createdAt": "2023-06-05T00:00:00Z",
  "itemCategories": [
    {
      "categoryId": 3
    }
  ]
}

###
// still need to make an api to update with the image, this one works without image upload
PUT {{url}}/admin/items/7
Content-Type: application/json

{
  "Title": "tablet",
  "description": "Updated description for the item.",
  "pricePerWeek": 25.00,
  "status": 2,
  "ImageSrc": "https://example.com/images/updated-item.jpg",
  "howToUse": "Updated usage instructions.",
  "Accesories": "Updated accessories list.",
  "weight": 3.0,
  "dimensions": "35x25 cm",
  "tip": "Updated usage tip.",
  "createdAt": "2023-06-10T00:00:00Z",
  "itemCategories": [
    {
      "categoryId": 1
    }
  ]
}
###
DELETE {{url}}/admin/items/4

###

//CATEGORIES
// -------------------------------
GET {{url}}/admin/categories
###

POST {{url}}/admin/categories
Content-Type: application/json

{
  "Name": "buiten",
  "IconName": "new-category-icon"
}

###
DELETE {{url}}/admin/categories/4
//LOCKERS
// -------------------------------
###
GET {{url}}/admin/lockers
###
GET {{url}}/admin/lockers/1

# ###
# POST {{url}}/admin/lockers
# Content-Type: application/json

# {
#   "LockerNumber": 231,
#   // choose an item that exists 
#   "itemId": 4
# }
###
# PUT {{url}}/lockers/1
# Content-Type: application/json

# {
#   "LockerNumber": 101,
#   // choose an item that exists 
#   "itemId": 1
# }

###
DELETE {{url}}/admin/lockers/1

###
#  Open/Close Locker (Manual Button Toggle)
# PUT /lockers/{id}/toggle


# POST {{url}}/lockers/unlock
# Content-Type: application/json

# {
#   "code": "23714#01"
# }

###
//RESERVATIONS
// -------------------------------

