@url = http://localhost:5159


//USERS 


GET {{url}}/users

### 
GET {{url}}/users/1

###
// for user
POST {{url}}/users
Content-Type: application/json

{
  "firstname": "Lisa",
  "lastname": "example",
  "phoneNumber": "32470123456",
  "email": "efhlzeuhfzeuifglz",
  "street": "Main Street 123",
  "city": "Kortrijk",
  "bus": null,
  "postalCode": "2000"
}

###
PUT {{url}}/users/1
Content-Type: application/json

{
  "firstname": "Philipp",
  "lastname": "example",
  "phoneNumber": "32470123456",
  "email": "jfeiojfofj.example.com",
  "street": "Main Street 123",
  "city": "Brussels",
  "bus": "02",
  "postalCode": "2000"
  
}
###

//ITEMS
// -------------------------------
###
// all products page  (delete categories )
GET {{url}}/items

###
// detail product page 
GET {{url}}/items/5
###
// get item with status available (for dropdown in product admin page)
GET {{url}}/items/available
###
GET {{url}}/items?categoryId=6
Accept: application/json
###

//CATEGORIES
// -------------------------------
GET {{url}}/categories
###


