name: Build and Publish image to Docker Hub
on:
  workflow_dispatch:
    inputs:
      build_frontend:
        description: 'Build frontend image'
        type: boolean
        default: true
        required: false
      build_backend:
        description: 'Build backend image'
        type: boolean
        default: true
        required: false
  # push:
  #   branches:
  #     - main
  #   paths:
  #     - 'frontend/**'
  #     - 'backend/**'

jobs:
  publish_images:
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v4

      - name: Create .env file from GitHub Secret
        run: echo "${{ secrets.ENV_FILE }}" > .env

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: woutjuuh02
          password: ${{ secrets.DOCKER_HUB_TOKEN }}

      - name: Build and push frontend
        if: ${{ inputs.build_frontend == true }}
        uses: docker/build-push-action@v5
        with:
          context: ./frontend
          platforms: linux/arm64
          # platforms: linux/amd64,linux/arm64
          push: true
          tags: woutjuuh02/deelfabriek-kortrijk-2025-frontend:latest

      - name: Build and push backend
        if: ${{ inputs.build_backend == true }}
        uses: docker/build-push-action@v5
        with:
          context: ./backend
          platforms: linux/arm64
          # platforms: linux/amd64,linux/arm64
          push: true
          tags: woutjuuh02/deelfabriek-kortrijk-2025-backend:latest